version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
    volumes:
      - ./postgres:/var/lib/postgresql/data

  backend:
    ports:
      - "8000:8000"
    build: 
      context: ./us-backend
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: ./us-frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  caddy-data:
  caddy-config:  

