services:
  db:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
    volumes:
      - ./postgres:/var/lib/postgresql/data
  app:
    ports: 
      - "8000:8000"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
       - db
    restart: unless-stopped
